# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "40...90"

  status:
    project:
      default:
        # Current baseline: ~46% lines, ~60% functions
        # Target: 80% per module, 90% overall (long-term goal)
        target: 50%
        threshold: 2%
    patch:
      default:
        # New code should have good coverage
        target: 70%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "test/**/*"
  - "Examples/**/*"
  - "Doc/**/*"
  # Generated files
  - "Src/y.tab.c"
